api_version = "2024-10"

[[extensions]]
name = "t:name"
handle = "costomer-tag-discount-app"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/customer-tag-discount/:functionId/new"
  details = "/app/customer-tag-discount/:functionId/:id"


  [extensions.input.variables]
  namespace = "$app:customer-tag-discount"
  key = "function-configuration"
